# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df9f82ab57aa57cea0a1239430a15ebe"
name = "Dealers-Internal Management"
application_url = "https://dealers.apps.tmgindustrial.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,write_app_proxy,read_themes,write_themes,write_content"

[app_proxy]
url = "/apps/dealer-locator"
prefix = "apps"
subpath = "dealer-locator"

[auth]
redirect_urls = [ "https://dealers.apps.tmgindustrial.com/api/auth" ]
